FROM --platform=linux/amd64 python:3.9

RUN apt-get update && apt-get install -y iperf3

RUN apt-get -y install hping3

COPY ./src /app/src
COPY requirements.txt /app

RUN pip3 install -r /app/requirements.txt

WORKDIR /app/src

EXPOSE 3001

CMD ["uvicorn", "main:app", "--host=0.0.0.0", "--port=3001"]
