FROM --platform=linux/amd64 python:3.9-slim

RUN apt-get update && \
    apt-get install iperf3 hping3 iputils-ping net-tools  -y

COPY ./src /app/src
COPY requirements.txt /app

RUN pip3 install -r /app/requirements.txt

WORKDIR /app/src

EXPOSE 3001

CMD ["uvicorn", "main:app", "--host=0.0.0.0", "--port=3001"]
