FROM python:3.9

COPY ./src /app/src
COPY requirements.txt /app

WORKDIR /app

RUN pip3 install -r requirements.txt

EXPOSE 3001

CMD ["uvicorn", "src.main:app", "--host=0.0.0.0", "--port=3001", "--reload"]